### ISSUE TITLE
please show me  the version of gcc and cuda 

### ISSUE THREAD

**Issue by chengcaoc** [lsrock1/maskrcnn_benchmark.cpp#1]
my  gcc is 4.9  and cuda is 9.0 

[  3%] Building CXX object source/rcnn/layers/CMakeFiles/layers.dir/batch_norm.cpp.o
[  6%] Building CXX object source/rcnn/layers/CMakeFiles/layers.dir/conv2d.cpp.o
[ 10%] Building CXX object source/rcnn/layers/CMakeFiles/layers.dir/cpu/ROIAlign_cpu.cpp.o
[ 13%] Building CXX object source/rcnn/layers/CMakeFiles/layers.dir/cpu/nms_cpu.cpp.o
[ 16%] Building CUDA object source/rcnn/layers/CMakeFiles/layers.dir/cuda/ROIAlign_cuda.cu.o
In file included from /usr/include/c++/4.9/atomic:38:0,
                 from /home/f1684326/anaconda3/envs/rcnn/lib/python2.7/site-packages/torch/include/c10/core/TensorTypeIdRegistration.h:15,
                 from /home/f1684326/anaconda3/envs/rcnn/lib/python2.7/site-packages/torch/include/c10/core/Backend.h:5,
                 from /home/f1684326/anaconda3/envs/rcnn/lib/python2.7/site-packages/torch/include/c10/core/Layout.h:3,
                 from /home/f1684326/anaconda3/envs/rcnn/lib/python2.7/site-packages/torch/include/ATen/core/Type.h:7,
                 from /home/f1684326/anaconda3/envs/rcnn/lib/python2.7/site-packages/torch/include/ATen/Type.h:2,
                 from /home/f1684326/anaconda3/envs/rcnn/lib/python2.7/site-packages/torch/include/ATen/Context.h:4,
                 from /home/f1684326/anaconda3/envs/rcnn/lib/python2.7/site-packages/torch/include/ATen/ATen.h:5,
                 from /home/f1684326/github/maskrcnn_benchmark_cpp/maskrcnn_benchmark.cpp/source/rcnn/layers/cuda/ROIAlign_cuda.cu:2:
/usr/include/c++/4.9/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
source/rcnn/layers/CMakeFiles/layers.dir/build.make:114: recipe for target 'source/rcnn/layers/CMakeFiles/layers.dir/cuda/ROIAlign_cuda.cu.o' failed
make[2]: *** [source/rcnn/layers/CMakeFiles/layers.dir/cuda/ROIAlign_cuda.cu.o] Error 1
CMakeFiles/Makefile2:212: recipe for target 'source/rcnn/layers/CMakeFiles/layers.dir/all' failed
make[1]: *** [source/rcnn/layers/CMakeFiles/layers.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by lsrock1** [comment]
hello!
if gcc is 4.x and cmake higher than 3.1,
set(CMAKE_CXX_STANDARD 11)
in cmake file
I forgot to set this option.

**Comment by lsrock1** [comment]
@chengcaoc I have solved your problem with cmake_nvcc_flags -std=c++11
