### ISSUE TITLE
anchors

### ISSUE THREAD

**Issue by RenAihua** [lsrock1/maskrcnn_benchmark.cpp#12]
hi，how can i generate anchors with libtorch on gpu device.

**Comment by lsrock1** [comment]
Anchor is generated in https://github.com/lsrock1/maskrcnn_benchmark.cpp/blob/master/source/rcnn/modeling/rpn/anchor_generator.cpp

**Comment by RenAihua** [comment]
Thankes！

**Comment by RenAihua** [comment]
@lsrock1  Thankes！
