### ISSUE TITLE
where is the official code of coco and rcnn？

### ISSUE THREAD

**Issue by TensorFlowWangHT** [lsrock1/maskrcnn_benchmark.cpp#15]
Excuse me, is the C ++ code for coco and rcnn in your source folder written by you or where is the official code?

**Comment by lsrock1** [comment]
COCO is from https://github.com/cocodataset/cocoapi/tree/master/common with some modification(c -> c++)
RCNN code is written by me. RCNN architecture is from maskrcnn-benchmark.

**Comment by TensorFlowWangHT** [comment]
@lsrock1 You are really too strong! I have much to learn from you! Did you write the .h file in include / rcnn? These .h files really helped a lot when using C ++ for object detection.

**Comment by lsrock1** [comment]
Thanks!
