### ISSUE TITLE
can't access https://www.dropbox.com/ for download models

### ISSUE THREAD

**Issue by jjqcat** [lsrock1/maskrcnn_benchmark.cpp#18]
I'm very interested in this project, and will use it for defect detection in images, marked the defect region( defect segment),  but fail to download models for test

**Comment by lsrock1** [comment]
I am not sure but i think you cannot access dropbox in your country. I will upload it in google drive.

**Comment by jjqcat** [comment]
thanks for your help.  can this project  train my own datasets?

**Comment by lsrock1** [comment]
I uploaded it to google drive!
