### ISSUE TITLE
Error in compiling (windows10 vs2015)

### ISSUE THREAD

**Issue by xiabc612** [lsrock1/maskrcnn_benchmark.cpp#4]
In the last step, after finishing cmake, I compiling the project in vs2015 and meet more than 400 errors, how can I solve them?
For example:
错误	C2131	表达式的计算结果不是常数	
maskrcnn_benchmark.cpp\source\coco\mask.cpp	123	
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C3863	不可指定数组类型“double ['函数']”	maskrcnn_benchmark.cpp\source\coco\mask.cpp	125	
严重性	代码	说明	项目	文件	行	禁止显示状态
错误		member "torch::jit::ArgumentSpecCreator::DEPTH_LIMIT" may not be initialized	layers	maskrcnn_benchmark.cpp\lib\libtorch\include\torch\csrc\jit\argument_spec.h	161

**Comment by lsrock1** [comment]
I found that my code is not compatible with vs. I really want to fix it but i dont have windows machine to reproduce this error. So, could you give me a full error message?
