### ISSUE TITLE
How to train the model to inference?

### ISSUE THREAD

**Issue by newforrestgump001** [lsrock1/maskrcnn_benchmark.cpp#5]
I wonder how to train the model to inference, By python, which framework ?
Thank you a lot!
Jack

**Comment by lsrock1** [comment]
You can use
https://github.com/facebookresearch/maskrcnn-benchmark
to train using same config file.
After training, you need to convert python pth to cpp pth.

**Comment by newforrestgump001** [comment]
@lsrock1  Thanks for your information!
Jack
