### ISSUE TITLE
parallel inference

### ISSUE THREAD

**Issue by soldierofhell** [lsrock1/maskrcnn_benchmark.cpp#7]
Hi, I noticed you reimplemented torch::nn::parallel::parallel_apply(). Is it supposed to be for multi-threaded evaluation? In general I wonder what would be the benefit od multi-threaded inference in C++ in comparision to Python?
Regards,

**Comment by lsrock1** [comment]
I reimplemented parallel because original implementation only supports tensor input and output.
In c++, i guess, can use real multi-thread, while python has GIL. I think C++ is faster in multi thread env.

**Comment by soldierofhell** [comment]
I wonder how to balance CPU execution between single execution where some ops can be potentially parallelized internally (especially with Intel MKL) with multi-execution. In other words what is the optimal strategy (given the numer of cores). Nevertheless, your implementation is a good example for this kind of experiments.

**Comment by lsrock1** [comment]
@soldierofhell thanks!
