### ISSUE TITLE
OpenCV

### ISSUE THREAD

**Issue by soldierofhell** [lsrock1/maskrcnn_benchmark.cpp#8]
Hi, are there any benefits from source compilation instead of using binaries? It takes hell lot of time :)
Regards,

**Comment by lsrock1** [comment]
Because of pytorch's ### cmake -DCMAKE_CXX_FLAGS=-D_GLIBCXX_USE_CXX11_ABI=0
option

**Comment by soldierofhell** [comment]
I mange to compile and run this simple example https://github.com/pytorch/examples/tree/master/cpp/custom-dataset with opencv binaries included in default colab ubuntu 18.04 even with Pre-cxx11 ABI version of libtorch
